![alt text](image-1.png)
파이썬 커널 연결되었는지 주피터 쓸 때 확인하기

## NumPy 기초

- 넘파이 패키지 로드

```python
import numpy as np
```

In [1]:
import numpy as np

### Python 리스트(배열) 과 NumPy 배열 비교

- 파이썬에 기존 리스트(배열) 자료구조 존재. 속도적면에서 NumPy가 우세

#### 파이썬으로 배열작업

In [5]:
prices = [10000, 15000, 12000, 30000, 25000] # 5개 가격이 든 배열
discount_prices = []

for price in prices:
    discount_prices.append(int(price*0.9)) #10% 할인

discount_prices

[9000, 13500, 10800, 27000, 22500]

#### NumPy 배열 작업

In [10]:

np_prices = np.array(prices) # 넘파이 배열로 변경
np_discount_prices = np_prices * 0.9   # for 문 쓸 필요 X, 리스트 항목 별 0.9 곱해줌
np_discount_prices

array([ 9000., 13500., 10800., 27000., 22500.])

- Numpy 배열은 반복문을 사용하지 않아도 배열 전체에 계산을 수행할 수 있음. `벡터화 연산`

## NumPy 배열 생성

In [11]:
array = np.array([1,2,3,4,5,6])
array

array([1, 2, 3, 4, 5, 6])

In [16]:
# 2차원 배열 [[ ]], 대괄호 두개시 2차원 배열 / [[[ ]]] 대괄호 3개시 3차원 배열
sales = np.array([
    [100, 120, 130],
    [90, 110, 150],
    [80, 140, 160]
])
sales

array([[100, 120, 130],
       [ 90, 110, 150],
       [ 80, 140, 160]])

In [14]:
# 파이썬 2차원 배열
tests = [
    [100, 120, 130],
    [90, 110, 150],
    [80, 140, 160]
]
tests

[[100, 120, 130], [90, 110, 150], [80, 140, 160]]

#### 배열 기본 속성

- `ndim` : 배열의 차원 수
- `shape` : 배열의 행과 열의 구조
- `size` : 전체 데이터 수
- `dtype` : 배열에 저장된 데이터타입

In [18]:
# ndim
print(np_prices.ndim, sales.ndim)

1 2


![alt text](image-2.png)
스패너 모양 －＞ 속성
정육면체 －＞ 함수 ： 뒤에 （） 와야 함。

In [19]:
# shape 행과 열의 구조
np_prices.shape

(5,)

In [20]:
sales.shape

(3, 3)

In [22]:
print (np_prices.size)
print(sales.size)

5
9


In [23]:
print(np_prices.dtype)
print(sales.dtype)

int64
int64


#### NumPy 데이터타입
- int8 : -128 ~ 127 (총 256)
- int16 : -32768 ~ 32767 (총 65536)
- int32 : 32비트 정수
- int64 : 64비트 정수(Numpy 기본 정수)
- uint8 : 0 ~ 255 / unsigned : - 부호가 없는
- uint16 : 0 ~ 65535
- float16 : 실수
- float32: 32비트 실수
- float64: 64비트 실수(Numpy 기본 실수)
- complex64 : 복소수
- complex128 : 128비트 복소수
- bool : True/False
- str_ : 문자열
- object_ : 객체

#### 배열 생성 함수

- 0이나 1로 채워진 기본 배열 생성 함수

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:

np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
# 파이썬 range() 와 동일
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# 균등배열(표준편차 등) / 최소값, 최대값, 중앙값, 평균값
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### 배열 연산

In [44]:
data = np.array([10, 20, 30, 40, 50])

In [46]:
# 사칙연산
print(data + 10)
print(data - 10)
print(data * 10)
print(data / 10)

[20 30 40 50 60]
[ 0 10 20 30 40]
[100 200 300 400 500]
[1. 2. 3. 4. 5.]


In [49]:
# 배열끼리 연산 / 열 개수가 같아야 계산 가능
quantity = np.array([2, 1, 3, 5, 4])
unit_price = np.array([10000, 15000, 12000, 8000, 20000])

sales_prices = unit_price * quantity

sales_prices

array([20000, 15000, 36000, 40000, 80000])

#### 기본 통계함수

- 평균, 최대/최소값, 중앙값, 표준편차 등

In [50]:
scores = np.array([80, 95, 70, 60, 100, 88])

In [52]:
np.sum(scores)

np.int64(493)

In [58]:
np.mean(scores)

np.float64(82.16666666666667)

In [59]:
np.max(scores)

np.int64(100)

In [60]:
np.min(scores)

np.int64(60)

In [61]:
np.median(scores)

np.float64(84.0)

In [62]:
np.std(scores)

np.float64(13.909429255804216)

#### 인덱싱 / 슬라이싱

- 파이썬 배열에서 기능과 유사

In [69]:
# 인덱싱
print(data[1])
print(data[-1])

# 슬라이싱
print(data[:]) # 배열전체
print(data[1:4]) # 1부터 3까지
print(data[:2])
print(data[3:])

20
50
[10 20 30 40 50]
[20 30 40]
[10 20]
[40 50]


In [70]:
# 2차원 배열
sales

array([[100, 120, 130],
       [ 90, 110, 150],
       [ 80, 140, 160]])

In [75]:
sales[0, 0] # 0번행 0번열 값 인덱싱

np.int64(100)

In [76]:
sales[1, :] #1번행의 모든 열 슬라이싱

array([ 90, 110, 150])

In [77]:
sales[:, 2] #모든 행의 2번열 값들을 슬라이싱

array([130, 150, 160])

#### 조건 필터링
- SQL WHERE 절과 동일, 조건에 맞는 데이터만 골라내기

In [84]:
print(prices)
np_prices

[10000, 15000, 12000, 30000, 25000]


array([10000, 15000, 12000, 30000, 25000])

In [79]:
prices >= 20000  ## 넘파이 배열이 아니라 파이썬 배열이라 안됨

TypeError: '>=' not supported between instances of 'list' and 'int'

In [82]:
np_prices >= 20000

[False False False  True  True]


In [87]:
condition = np_prices >= 20000
condition

array([False, False, False,  True,  True])

In [90]:
# np_prices에서 True인 값들만 출력
np_prices[condition]
np_prices[np_prices >= 20000]

array([30000, 25000])

In [91]:
datas = np.array([10, -1, 80, 999, 30, 120])
datas

array([ 10,  -1,  80, 999,  30, 120])

In [104]:
# & : and, | : or
datas[(datas >= 0) & (datas <= 100)]

array([10, 80, 30])

#### ★결측값★  핸들링

- 실제 데이터에서 값이 비어있는 경우, 이를 결측치/결측값이라고 함
- 일반적으로 `NULL`, 파이썬에서는 `None`, NumPy에서는 `np.nan` 로 표현

In [ ]:
temperatures = np.array([22.5, 23.0, np.nan, 25.1, 21.8])

In [109]:
temperatures

array([22.5, 23. ,  nan, 25.1, 21.8])

In [107]:
# 평균값 
temperatures.mean()

np.float64(nan)

In [108]:
temperatures.min()

np.float64(nan)

In [111]:
# np.nan 뺀 평균
np.nanmean(temperatures)

np.float64(23.099999999999998)

In [112]:
np.isnan(temperatures)

array([False, False,  True, False, False])

In [116]:
temperatures[~np.isnan(temperatures)]

array([22.5, 23. , 25.1, 21.8])

- 결측치 정리 방법 : 결측치는 제거하거나(건수 감소), 나머지 평균값을 임의로 기입하거나, 기본통계에서 도출할 수 있는 다른 값들로 채우기(최소값, 최대값, 중앙값 ...)


#### 이상치 핸들링

- 일반적인 범위를 벗어나는 비정상 데이터.
- 예로 부산 1월 일별 평균기온: -90도

In [117]:
temperatures = np.array([22.5, 23.0, np.nan, 25.1, 999.0, 21.8, -99.0])
temperatures

array([ 22.5,  23. ,   nan,  25.1, 999. ,  21.8, -99. ])

In [119]:
valid_temps = temperatures[
    (~np.isnan(temperatures)) &     #nan은 무조건 제거
    (temperatures >= 15.0 ) &       # 최저기온이 15 아래로 내려갈 수 없으므로 제거
    (temperatures <= 50)            # 최고기온이 50도 이상 올라갈 수 없어 제거
]
valid_temps

array([22.5, 23. , 25.1, 21.8])

- 전처리(PreProcessing) - 분석 이전에 이상치, 결측치를 없애는 작업

### 실습

#### 기온데이터 전처리

In [122]:
temperatures = np.array([22.5, 23.0, np.nan, 25.1, 999.0, 21.8, -99.0, 24.0, 23.5, np.nan])
temperatures

array([ 22.5,  23. ,   nan,  25.1, 999. ,  21.8, -99. ,  24. ,  23.5,
         nan])

- 결측값 개수 출력
- 결측값, 이상치 제거
- 정상 데이터 출력
- 평균 기온 출력
- 최고 기온 출력
- 최저 기온 출력

In [124]:
# 결측값 출력
np.isnan(temperatures)

array([False, False,  True, False, False, False, False, False, False,
        True])

In [127]:
# 결측값 갯수
print(np.isnan(temperatures).sum())
missing_count = np.isnan(temperatures).sum()

2


In [130]:
# 결측값, 이상치 제거 및 정상 데이터 출력
valid_temps = temperatures[
    (~np.isnan(temperatures)) &
    (temperatures >= -15.0) &
    (temperatures <= 50.0)
]

valid_temps

array([22.5, 23. , 25.1, 21.8, 24. , 23.5])

In [134]:
valid_temps.mean()
valid_temps.max()
valid_temps.min()

np.float64(21.8)

### 매출 데이터 전처리

- 결측값 개수 출력
- 결측값 제외
- 0원 10만원 내의 정상 매출만 남김
- 정상 매출의 평균, 최대값, 최소값 출력
- 정상 매출에서 평균이상인 값만 출력

In [135]:
# 파이썬 리스트에서 None 대신 np.nan으로 결측치를 입력하면 NumPy 패키지 연산 가능
raw_sales = [12000, 15000, np.nan, 30000, -5000, 25000, 9999999, 18000, np.nan, 22000]

raw_sales

[12000, 15000, nan, 30000, -5000, 25000, 9999999, 18000, nan, 22000]

In [136]:
# NumPy 배열로 변경
np_raw_sales = np.array(raw_sales)

np_raw_sales

array([ 1.200000e+04,  1.500000e+04,           nan,  3.000000e+04,
       -5.000000e+03,  2.500000e+04,  9.999999e+06,  1.800000e+04,
                 nan,  2.200000e+04])

In [137]:
# 결측값 확인
np.isnan(raw_sales)

array([False, False,  True, False, False, False, False, False,  True,
       False])

In [138]:
np.isnan(raw_sales).sum()

np.int64(2)

In [140]:
np_raw_sales[
    (~np.isnan(np_raw_sales)) &
    (np_raw_sales >= 0) &
    (np_raw_sales <= 100000)
]

array([12000., 15000., 30000., 25000., 18000., 22000.])

In [141]:
valid_sales = np_raw_sales[
    (~np.isnan(np_raw_sales)) &
    (np_raw_sales >= 0) &
    (np_raw_sales <= 100000)
]

valid_sales

array([12000., 15000., 30000., 25000., 18000., 22000.])

In [145]:
mean_sales = valid_sales.mean()
valid_sales.min()
valid_sales.max()

np.float64(30000.0)

In [147]:
# 평균 매출액보다 높은 매출 찾기
valid_sales[valid_sales >= mean_sales]

array([30000., 25000., 22000.])